# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true

# Mod properties
mod_id = tailormade
mod_version = 1.0.4
mod_name=Tailormade
mod_license=MIT License
maven_group = com.tailormade.tailor
archives_name = tailormade
enabled_platforms = neoforge

# Minecraft properties
minecraft_version = 1.21.1
minecraft_version_range=[1.21.1]

# Dependencies
architectury_api_version = 13.0.11
fabric_loader_version = 0.19.5
neoforge_version = 21.1.219
loader_version_range = [1,)